services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: fastapi_user
      MYSQL_PASSWORD: fastapi_pass
      MYSQL_DATABASE: fastapi_db
      MYSQL_ROOT_PASSWORD: rootpass
      DB_HOST: db
      DB_PORT: 3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - MYSQL_USER=fastapi_user
      - MYSQL_PASSWORD=fastapi_pass
      - MYSQL_DATABASE=fastapi_db
      - MYSQL_ROOT_PASSWORD=rootpass
      - DB_HOST=db
      - DB_PORT=3306
